#!/bin/sh

xrandr --output DP-3 --primary --mode 1920x1080 --rate 164.92 \
--output DP-2 --mode 1920x1080 --rate 165.00 --right-of DP-3

setxkbmap -option caps:swapescape
xmodmap -e "keysym Menu = Super_R"
