[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center", "--transition-duration", "2"]
set = true


[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.hyprland]
input_path = './templates/hyprland-colors.css'
output_path = '~/.config/hypr/colors.conf'

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.swayc]
input_path = './templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'
