general {
    lock_cmd = pidof hyprlock || hyprlock --grace 20 # Give me some time before I have to type my password!
    before_sleep_cmd = loginctl lock-session    # lock before suspend
}

# Lock the screen
listener {
    timeout = 600                               # 10 min
    on-timeout = loginctl lock-session
}

# Suspend the system
listener {
    timeout = 900                               # 15 min
    on-timeout = systemctl suspend
}

